import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import PostsList from '../components/PostsList';



export default function Home() {
  const [postCategory, setPostCategory]=useState(null)
  const handlePostCategorySelect = (postCategoryId) => {
    console.log("Selected category: ", postCategoryId)
    setPostCategory(postCategoryId)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Własny pokój
        </h1>

        <p className={styles.description}>
          Witaj w moim wirtualnym domu
        </p>
        <NavBar onPostCategorySelect={handlePostCategorySelect}/>
        <PostsList selectedPostCategory={postCategory}/>
        <div>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
